import "./components/burger";
import "./components/slider";
import "./components/tabs";
import "./components/scrolling";
import "./components/phoneMask";
import "./components/modals";
import "./components/cards";
import "./components/form";
import "./components/user";